Automated build + update doc for 2.4.0
IonDen/ion.rangeSlider pull request #691
Opened 2020-03-31 09:31 UTC by djibe

First PR : sets up all devDependencies + scripts to compile changes instantly.
+ updates docs and bower accordingly.

Next PR will be Material skin.

2020-03-31 09:32 UTC, djibe commented
If you want to play with material skin right now : https://jsfiddle.net/djibe89/z31rxhot/17/

2020-04-23 15:36 UTC, djibe commented
Hi @IonDen . COuld you merge my PR so I can submet my Material skin ?

Thanks,
See you

2020-04-23 15:37 UTC, IonDen commented
@djibe, you did not resolve 2 minor issues.

2020-04-23 19:53 UTC, djibe commented
Ooops.
Tried to figure out what those 2 minor issues are.
Do you have a hint so I can fix what you don't like ?
Your fan,
djibe

2020-04-23 20:33 UTC, IonDen requested changes

2020-04-23 20:33 UTC, IonDen commented
Ooops, sorry, I did not press the button)

2020-04-23 20:58 UTC, djibe commented
Done. Thx

2020-04-27 09:07 UTC, djibe commented
Hi @IonDen 
Everything finally fixed :D
Thx

2020-04-27 10:09 UTC, IonDen commented
Hi, @djibe, I will try to find some time this week to merge it.
Remember I will need not only merge it, but update a website and publish new version to NPM.

2020-04-27 17:54 UTC, djibe commented
I know and I appreciate your time.
See you.

2026-08-23 13:35 UTC, IonDen commented
Thanks, @djibe, for taking a first pass at the build tooling, the compile-prefix-minify CSS pipeline is a solid starting point and it is being folded into #802, with a pointer to #798 for the bower.json fix that rode along in the same diff. It cannot be merged as one PR because it also hand-edits the version number and reflows readme wording that a release script should own instead, and one-concern-per-change is the policy this project is establishing before it even has a build or test harness. #802 and #798 are the ones to watch, or comment on either directly. Closing this PR now.

2026-08-23 13:35 UTC, closed without merging